-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 12:21:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_virtualpet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_virtualpet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_virtualpet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `db_virtualpet` ;

-- -----------------------------------------------------
-- Table `db_virtualpet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_virtualpet`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('ROLE_USER', 'ROLE_ADMIN') NOT NULL DEFAULT 'ROLE_USER',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_virtualpet`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_virtualpet`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pet_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_virtualpet`.`users_has_pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_virtualpet`.`users_has_pets` (
  `users_id` INT NOT NULL,
  `pets_id` INT NOT NULL,
  `pet_name` VARCHAR(45) NOT NULL,
  `pet_color` ENUM('RED', 'GREEN', 'BLUE') NOT NULL,
  `pet_energylevel` DECIMAL(3,2) NOT NULL DEFAULT 0.5,
  `pet_mood` DECIMAL(3,2) NOT NULL DEFAULT 0.5,
  `pet_hungrylevel` DECIMAL(3,2) NOT NULL DEFAULT 0.5,
  PRIMARY KEY (`users_id`, `pets_id`),
  INDEX `fk_users_has_pets_pets1_idx` (`pets_id` ASC) VISIBLE,
  INDEX `fk_users_has_pets_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_pets_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_virtualpet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_pets_pets1`
    FOREIGN KEY (`pets_id`)
    REFERENCES `db_virtualpet`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
