openapi: 3.0.1
info:
  title: Virtual Pet API
  description: API for managing virtual pets.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /auth/signup:
    post:
      summary: Register a new user
      description: Endpoint for registering a new user in the system.
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        description: Data required to register a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserDto'
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Validation error
        '500':
          description: Internal server error

  /auth/login:
    post:
      summary: Authenticate a user
      description: Endpoint for user login, returning a JWT token upon successful authentication.
      operationId: authenticateUser
      tags:
        - Authentication
      requestBody:
        description: User credentials for authentication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserDto'
      responses:
        '200':
          description: User successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
        '401':
          description: Invalid credentials
        '500':
          description: Internal server error

  /pet/create:
    post:
      summary: Create pet for authenticated user
      description: This endpoints makes possible creating a new virtual pet for the authenticated user
      operationId: createUserPet
      tags:
        - UserPet
      requestBody:
        description: Requested data to create a new pet
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPetCreateDto'
      responses:
        '200':
          description: Pet successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPet'
        '400':
          description: Error request, validation has failed.
        '401':
          description: User not authenticated
        '500':
          description: Server internal error.
      security:
        - bearerAuth: [] # Autenticaci贸n con JWT

  /pet/read:
    post:
      summary: Get pets for authenticated user
      description: This endpoints retrieves all pets owned by the authenticated user, and all pets of all owners if role user is ADMIN
      operationId: getAllPets
      tags:
        - UserPet
      responses:
        '200':
          description: Pet list successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPet'
        '400':
          description: Error request, validation has failed.
        '401':
          description: User not authenticated
        '404':
          description: User not found
        '500':
          description: Server internal error.
      security:
        - bearerAuth: [] # Autenticaci贸n con JWT

  /update/{petUserId}/{action}:
    put:
      summary: Updates user pet values upon the required action
      operationId: updatePet
      tags:
        - UserPet
      security:
        - bearerAuth: []  # Autenticaci贸n con JWT
      parameters:
        - name: petUserId
          in: path
          required: true
          description: User pet unique identifier
          schema:
            type: integer
            format: int32
        - name: action
          in: path
          required: true
          description: "Action to be carried out with the pet (example: FEED, PLAY, READ, etc.)"
          schema:
            type: string
            enum: [FEED, PLAY, READ, SLEEP, SUNGLASSES, BEACH]
      responses:
        "200":
          description: "Pet values successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPet"
        "400":
          description: "Wrong request (invalid parameters)"
        "401":
          description: "Not authorized"
        "404":
          description: "Pet not found"
        "500":
          description: "Server internal error"

  /delete/{petUserId}:
    delete:
      summary: Delete pet of authenticated user
      operationId: deletePet
      tags:
        - UserPet
      security:
        - bearerAuth: []  # Autenticaci贸n con JWT
      parameters:
        - name: petUserId
          in: path
          required: true
          description: User pet unique identifier
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: "No content: Pet successfully deleted"
        "400":
          description: "Wrong request (invalid parameters)"
        "401":
          description: "Not authorized"
        "404":
          description: "Pet not found"
        "500":
          description: "Server internal error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserPetCreateDto:
      type: object
      properties:
        userId:
          type: integer
          description: User unique identifier.
        petName:
          type: string
          description: Pet name.
        animal:
          type: string
          description: Pet type (i.e. 'MONKEY', 'LION', 'KANGAROO', 'KOALA').
          enum:
            - MONKEY
            - LION
            - KANGAROO
            - KOALA
        petColor:
          type: string
          description: Pet type (i.e. 'RED', 'YELLOW', 'BLUE', 'GREEN').
          enum:
            - RED
            - YELLOW
            - BLUE
            - GREEN
      required:
        - petName
        - animal
        - petColor

    UserPet:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: User pet unique identifier.
        userId:
          type: integer
          format: int32
          description: User identifier.
        name:
          type: string
          description: Pet name.
        animal:
          $ref: "#/components/schemas/Animal"
        petColor:
          $ref: "#/components/schemas/PetColor"
        petEnergyLevel:
          type: number
          format: float
          description: Pet energy level.
        petMood:
          type: number
          format: float
          description: Pet energy level.
        petHungryLevel:
          type: number
          format: float
          description: Pet hunger level

    RegisterUserDto:
      type: object
      properties:
        userName:
          type: string
          description: Username of the new user.
        password:
          type: string
          description: Password of the new user.
      required:
        - userName
        - password

    LoginUserDto:
      type: object
      properties:
        userName:
          type: string
          description: Username of the user.
        password:
          type: string
          description: Password of the user.
      required:
        - userName
        - password

    LoginResponseDto:
      type: object
      properties:
        token:
          type: string
          description: JWT token for the authenticated user.
        expiresIn:
          type: integer
          description: Token expiration time in milliseconds.

    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the user.
        userName:
          type: string
          description: Username of the user.
        password:
          type: string
          description: User password.
        role:
          type: string
          description: User role (ROLE_ADMIN, ROLE_USER).
      required:
        - userName
        - password

    Animal:
      type: string
      enum: [MONKEY, KANGAROO, KOALA, LION]
      description: Available animals

    PetColor:
      type: string
      enum: [RED, YELLOW, GREEN, BLUE]
      description: Available pet colors